
#define CONFIG_VK_VALIDATION_LAYERS    1
#define CONFIG_VK_MAX_FRAMES_IN_FLIGHT 2

#define CONFIG_SHADER_SPV_PATH "./shader.spv"

#define CONFIG_WINDOW_RESIZABLE 1
#define CONFIG_WINDOW_WIDTH     800
#define CONFIG_WINDOW_HEIGHT    600

#define CONFIG_DEBUG_VERBOSE 1
