
struct VertexInput {
    float2 position;
    float3 color;
};

struct VertexOutput {
    float3 color;
    float4 sv_position : SV_Position;
};

[shader("vertex")]
VertexOutput vert_main(VertexInput input) {
    VertexOutput output;

    output.sv_position = float4(input.position, 0.0, 1.0);
    output.color = input.color;

    return output;
}

[shader("fragment")]
float4 frag_main(VertexOutput in_vert) : SV_Target
{
    float3 color = in_vert.color;

    return float4(color, 1.0);
}
